input("enter your name")
input ("enter your age")
num1=int(input("enter first number"))
num2=input ("second number")
num2=int(num2)
c=(num1 + num2)
print("the sum is",c)
d=(num1-num2)
print("the difference is",d)
e=(num1*num2)
print("the product is",e)
f=(num1/num2)
print("the division is %.2f" %f)